### ISSUE TITLE
查词没出现授权要求，并且查询过一会工作流就自动消失了

### ISSUE THREAD

**Issue by Tobiasll** [alswl/shanbay-alfred2#5]
sb 查词时显示查询中，过一会儿就自动消失了，没法授权
![image](https://user-images.githubusercontent.com/34811564/108478119-0dc8eb00-72cf-11eb-8bf6-d67b557aa13e.png)
![image](https://user-images.githubusercontent.com/34811564/108478159-1ae5da00-72cf-11eb-8646-201a36524f6e.png)

**Comment by alswl** [comment]
看项目描述：

> 扇贝词典 alfred2/3/4 workflow, 支持查询和添加单词到自己词库。update：由于扇贝关闭开放 API，本项目已经不可正常工作。
